# Generated by Django 4.2.6 on 2023-10-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('intro', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
