# Generated by Django 4.2.6 on 2023-10-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_hero_img_summary_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='img',
            new_name='image',
        ),
    ]
