# Generated by Django 4.2.6 on 2023-10-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_achievements_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.AddField(
            model_name='achievements',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='companies', to='resume.company'),
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='hired_companies', to='resume.company'),
        ),
    ]
