# Generated by Django 4.2.6 on 2023-10-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_company_remove_experience_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='SocialMenu',
            new_name='SocialMediaItem',
        ),
    ]
