# Generated by Django 4.2.6 on 2023-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_rename_achievements_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='resume.company'),
        ),
    ]
