# Generated by Django 4.2.6 on 2023-10-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_alter_socialmediaitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='desired_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
